language: clojure
before_script: lein ancient
sudo: required
services:
  - docker
script: lein cloverage --codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
