version: "3.7"
services:
  mysql8.0:
    image: mysql:8.0.13
    container_name: mysql8.0.13
    ports:
      - 30000:33060
    environment:
      - MYSQL_DATABASE=mysqlx-clj
      - MYSQL_USER=clj
      - MYSQL_PASSWORD=s3cr3t
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./mysql8.0/logs:/var/log/mysql:rw
      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./common:/app:ro